- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 'master'
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-xml
    - id: check-json
    - id: pretty-format-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
